import {
  AlertTriangle,
  Brain,
  Coins,
  Database,
  Droplets,
  HeartPulse,
  Landmark,
  Leaf,
  Network,
  Scan,
  Sprout,
} from 'lucide-react';

const BlueprintDiagram = () => (
  <div className="w-full overflow-x-auto rounded-2xl border border-slate-200 bg-slate-50 p-6 shadow-inner md:p-10" data-testid="blueprint-diagram">
    <div className="min-w-[800px]">
      <div className="mb-12 text-center"><h2 className="font-serif text-3xl font-bold text-slate-900">Systemic Coherence</h2><p className="mt-2 text-sm font-bold uppercase tracking-widest text-slate-500">A Blueprint for a Regenerative Civilization</p></div>
      <div className="relative mb-12 grid grid-cols-3 gap-8">
        <div className="absolute left-1/4 right-1/4 top-1/2 -z-10 hidden h-1 border-t-2 border-dashed border-slate-300 md:block" />
        <section className="relative rounded-xl border border-rose-100 bg-white p-6 shadow-sm"><div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-rose-100 px-3 py-1 text-xs font-bold uppercase text-rose-800">The Problem</div><h3 className="mb-6 mt-2 text-center font-bold text-slate-800">A Systemic Fracture</h3><div className="space-y-6"><div className="text-center"><AlertTriangle className="mx-auto mb-2 text-rose-500" size={32} /><h4 className="text-sm font-bold text-slate-700">Nutrient Decline</h4><p className="mt-1 text-xs text-slate-500">Changes in crop genetics, soil, and food systems can reduce mineral density.</p></div><div className="text-center"><Brain className="mx-auto mb-2 text-rose-500" size={32} /><h4 className="text-sm font-bold text-slate-700">Hidden Hunger</h4><p className="mt-1 text-xs text-slate-500">Calories can rise while micronutrient adequacy remains uneven.</p></div><div className="border-t border-slate-100 pt-4 text-center"><Network className="mx-auto mb-2 text-stone-600" size={32} /><h4 className="text-sm font-bold text-slate-700">Severed Soil Networks</h4><p className="mt-1 text-xs text-slate-500">Tillage and chemical pressure can disrupt fungal relationships.</p></div></div></section>
        <section className="relative rounded-xl bg-emerald-900 p-6 text-white shadow-lg"><div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-emerald-500 px-3 py-1 text-xs font-bold uppercase text-emerald-950">The Architecture</div><h3 className="mb-6 mt-2 text-center font-bold text-emerald-50">Rewarding Regeneration</h3><div className="space-y-4"><div className="flex items-center rounded border border-emerald-700/50 bg-emerald-800/50 p-3"><Scan className="mr-3 flex-shrink-0 text-emerald-400" size={24} /><div><h4 className="text-xs font-bold">MRV Verification</h4><p className="text-[10px] text-emerald-200 opacity-80">Spectral, laboratory, field, and chain-of-custody evidence</p></div></div><div className="flex items-center rounded border border-emerald-700/50 bg-emerald-800/50 p-3"><Database className="mr-3 flex-shrink-0 text-emerald-400" size={24} /><div><h4 className="text-xs font-bold">DAVL Ledger</h4><p className="text-[10px] text-emerald-200 opacity-80">Versioned, auditable verification records</p></div></div><div className="flex items-center rounded border border-emerald-700/50 bg-emerald-800/50 p-3"><Coins className="mr-3 flex-shrink-0 text-emerald-400" size={24} /><div><h4 className="text-xs font-bold">RESTA / NIDM Policy</h4><p className="text-[10px] text-emerald-200 opacity-80">Public support linked to verified outcomes</p></div></div></div></section>
        <section className="relative rounded-xl border border-blue-100 bg-white p-6 shadow-sm"><div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-blue-100 px-3 py-1 text-xs font-bold uppercase text-blue-800">The Result</div><h3 className="mb-6 mt-2 text-center font-bold text-slate-800">A Self-Perpetuating Cycle</h3><div className="relative flex h-48 items-center justify-center"><div className="absolute h-32 w-32 animate-[spin_20s_linear_infinite] rounded-full border-4 border-dashed border-blue-200" /><div className="absolute left-1/2 top-0 -translate-x-1/2 -translate-y-1/2 rounded-full border border-blue-200 bg-white p-1 shadow-sm"><Sprout size={20} className="text-emerald-600" /></div><div className="absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 rounded-full border border-blue-200 bg-white p-1 shadow-sm"><HeartPulse size={20} className="text-rose-500" /></div><div className="absolute left-0 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full border border-blue-200 bg-white p-1 shadow-sm"><Scan size={20} className="text-blue-500" /></div><div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 rounded-full border border-blue-200 bg-white p-1 shadow-sm"><Landmark size={20} className="text-amber-500" /></div><div className="z-10 flex h-20 w-20 flex-col items-center justify-center rounded-full border border-blue-100 bg-blue-50 p-2 text-center"><span className="text-[10px] font-bold leading-tight text-blue-800">Bioregion<br />Flourishes</span></div></div></section>
      </div>
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-100 p-3"><h4 className="text-center text-sm font-bold uppercase tracking-wider text-slate-800">Paradigm Shift: From Extractive to Regenerative Metrics</h4></div><div className="grid grid-cols-3 text-xs md:text-sm"><div className="border-b border-r border-slate-200 bg-slate-50 p-3 font-bold text-slate-600">Focus Area</div><div className="border-b border-r border-slate-200 bg-slate-50 p-3 font-bold text-slate-600">Traditional Metric</div><div className="border-b border-slate-200 bg-emerald-50 p-3 font-bold text-emerald-700">Action-Aligned Metric</div><div className="flex items-center border-b border-r border-slate-200 p-3"><Leaf size={14} className="mr-2 text-stone-500" /> Soil Health</div><div className="border-b border-r border-slate-200 p-3 text-slate-500">Emissions per unit of yield</div><div className="border-b border-slate-200 p-3 font-medium">Sequestered carbon, aggregation, biology, and uncertainty</div><div className="flex items-center border-b border-r border-slate-200 p-3"><Droplets size={14} className="mr-2 text-blue-500" /> Water Quality</div><div className="border-b border-r border-slate-200 p-3 text-slate-500">Water used per unit of output</div><div className="border-b border-slate-200 p-3 font-medium">Reduced nutrient loss, infiltration, and environmental flows</div><div className="flex items-center border-r border-slate-200 p-3"><HeartPulse size={14} className="mr-2 text-rose-500" /> Social / Equity</div><div className="border-r border-slate-200 p-3 text-slate-500">Labor cost efficiency</div><div className="p-3 font-medium">Farmer wellbeing, agency, affordability, and civic health</div></div></div>
    </div>
  </div>
);

export default BlueprintDiagram;
